import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{AnimatePresence,motion}from'framer-motion';
import{ArrowDownRight,ArrowUpRight,ArrowLeft,ArrowRight,Menu,X,MoveRight,Search}from'lucide-react';
import'./style.css';
import hero01 from'./assets/gallery-hero.png';
import hero02 from'./assets/gallery-hero-02.png';
import hero03 from'./assets/gallery-hero-03.png';
import figurativeWork from'./assets/work-figurative.png';
import landscapeWork from'./assets/work-landscape.png';
import stillLifeWork from'./assets/work-still-life.png';
import windowPortraitWork from'./assets/work-window-portrait.png';
import readingRoomWork from'./assets/work-reading-room.png';
import nightOrchardWork from'./assets/work-night-orchard-ii.png';
import botanicalInkWork from'./assets/work-botanical-ink.png';
import winterFieldWork from'./assets/work-winter-field.png';
import geometricTextileWork from'./assets/work-geometric-textile.png';

const works=[
 {id:'01',title:'A Quiet Measure',artist:'Mara Veldt',year:'2026',medium:'Oil, ash and wax on linen',size:'180 × 240 cm',tone:'rust',status:'Available'},
 {id:'02',title:'After the Flood',artist:'Jonas Rhee',year:'2025',medium:'Pigment and graphite on canvas',size:'210 × 165 cm',tone:'blue',status:'On hold'},
 {id:'03',title:'Held Light No. 7',artist:'Sofia Marin',year:'2026',medium:'Oil and marble dust on linen',size:'150 × 120 cm',tone:'cream',status:'Available'},
 {id:'04',title:'Night Orchard',artist:'Ivo Kers',year:'2024',medium:'Oil and cold wax on panel',size:'122 × 98 cm',tone:'dark',status:'Private collection'},
 {id:'05',title:'The Space Beside Her',artist:'Noor Abeni',year:'2026',medium:'Oil on Belgian linen',size:'160 × 125 cm',tone:'portrait',image:figurativeWork,status:'Available',genre:'Figurative'},
 {id:'06',title:'Low Water, Evening',artist:'Lucien Vale',year:'2025',medium:'Oil and cold wax on linen',size:'110 × 180 cm',tone:'landscape',image:landscapeWork,status:'Available',genre:'Landscape'},
 {id:'07',title:'Quince in October',artist:'Emilia Sanz',year:'2026',medium:'Oil, egg tempera and wax on panel',size:'140 × 95 cm',tone:'still-life',image:stillLifeWork,status:'On hold',genre:'Still life'},
 {id:'08',title:'The Quiet Hour',artist:'Ansel Devereux',year:'2025',medium:'Oil on linen',size:'165 × 110 cm',tone:'portrait',image:windowPortraitWork,status:'Available',genre:'Figurative'},
 {id:'09',title:'Red Chair, 16:40',artist:'Clara Mertens',year:'2026',medium:'Casein and oil on wood panel',size:'105 × 168 cm',tone:'interior',image:readingRoomWork,status:'Available',genre:'Interior'},
 {id:'10',title:'Orchard After Midnight',artist:'Yuna Seo',year:'2025',medium:'Oil and encaustic on linen',size:'145 × 145 cm',tone:'nocturne',image:nightOrchardWork,status:'On hold',genre:'Surrealism'},
 {id:'11',title:'Field Notes No. 3',artist:'Amina Kader',year:'2026',medium:'Sumi ink, mineral pigment and graphite on paper',size:'78 × 118 cm',tone:'works-paper',image:botanicalInkWork,status:'Available',genre:'Works on paper'},
 {id:'12',title:'Blue Hour Ridge',artist:'Elias Voss',year:'2024',medium:'Oil, marble dust and graphite on linen',size:'120 × 210 cm',tone:'landscape',image:winterFieldWork,status:'Private collection',genre:'Landscape'},
 {id:'13',title:'Counterweight',artist:'Tess Nwosu',year:'2026',medium:'Acrylic, dyed linen and hand stitching',size:'190 × 128 cm',tone:'textile',image:geometricTextileWork,status:'Available',genre:'Mixed media'},
];
const homepageWorkOrder=['08','02','11','05','13','03','09','06','10','01','12','07','04'];
const homepageWorks=homepageWorkOrder.map(id=>works.find(work=>work.id===id)).filter(Boolean);
const nav=[['Collection','collection'],['Artists','artists'],['Exhibitions','exhibitions'],['Journal','journal'],['Visit','visit']];
function go(p){location.hash=p==='home'?'':p;scrollTo({top:0,behavior:'smooth'})}
function Nav({page}){const[open,setOpen]=useState(false);return <><div className="nowbar">NOW ON VIEW <span>OPEN GROUND — MARA VELDT</span><button onClick={()=>go('exhibitions')}>VIEW DETAILS →</button></div><header className="nav"><button className="brand" onClick={()=>go('home')} aria-label="Vant Lore home">VANT<span>—</span>LORE</button><nav>{nav.map(([n,p])=><button key={p} className={page===p?'on':''} onClick={()=>go(p)}>{n}</button>)}</nav><button className="search" aria-label="Search collection" onClick={()=>go('collection')}><Search size={16}/></button><button className="inquire" onClick={()=>go('visit')}>Private viewing <ArrowUpRight size={15}/></button><button className="menub" aria-label="Toggle menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header><AnimatePresence>{open&&<motion.div className="drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}}>{nav.map(([n,p],i)=><motion.button key={p} initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} transition={{delay:i*.06}} onClick={()=>{go(p);setOpen(false)}}>{n}<span>0{i+1}</span></motion.button>)}</motion.div>}</AnimatePresence></>}
const Reveal=({children,className='',delay=0})=><motion.div className={className} initial={{opacity:0,y:32}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.85,delay,ease:[.2,.8,.2,1]}}>{children}</motion.div>;
function Art({tone,image,className=''}){return <div className={`art ${tone} ${image?'hasImage':''} ${className}`}>{image?<img src={image} alt=""/>:<><i/><b/><em/></>}</div>}
const collectorNotes=[
 {quote:'The team made choosing—and living with—the work feel unhurried, informed, and entirely personal.',name:'A. M.',detail:'Private collector · London'},
 {quote:'Every detail, from the first viewing through to installation, was handled with quiet precision.',name:'J. & L.',detail:'Collectors · Antwerp'},
 {quote:'We came for one painting and left with a lasting relationship to the artist’s practice.',name:'R. K.',detail:'Private collector · Amsterdam'},
];
function CollectorNotes(){return <section className="collectorNotes" aria-labelledby="collector-notes-title"><div className="notesIntro"><small>COLLECTOR NOTES / PRIVATE CLIENTS</small><h2 id="collector-notes-title">Trusted beyond<br/>the <i>gallery walls.</i></h2><p>Thoughtful guidance, discreet service, and considered placement—from a first conversation to final installation.</p></div><div className="notesList">{collectorNotes.map((note,i)=><Reveal key={note.name} className={`collectorNote note${i+1}`} delay={i*.07}><span aria-hidden="true">“</span><blockquote>{note.quote}</blockquote><p><b>{note.name}</b>{note.detail}</p></Reveal>)}</div></section>}
function Footer(){return <><CollectorNotes/><section className="newsletter"><div><small>THE GALLERY LETTER</small><h2>Exhibitions, studio visits,<br/>and new work—occasionally.</h2></div><form onSubmit={e=>e.preventDefault()}><label htmlFor="email">Email address</label><input id="email" type="email" placeholder="you@example.com" required/><button>Subscribe <ArrowUpRight/></button></form></section><footer><div className="footmark">VANT—LORE</div><div><small>GALLERY</small><p>Kattendijkdok 14<br/>2000 Antwerp, Belgium</p><p>Thu—Sat, 11:00—18:00</p></div><div><small>ENQUIRIES</small><p>studio@vantlore.gallery<br/>+32 3 555 01 48</p><p>Press · Shipping · Advisory</p></div><div><small>FOLLOW</small><p>Instagram<br/>Artsy</p><p>Privacy · Terms</p></div><button onClick={()=>scrollTo({top:0,behavior:'smooth'})}>Back to top ↑</button></footer></>}
const heroSlides=[
 {src:hero01,alt:'A monumental rust and blue abstract painting installed in the Antwerp gallery',exhibition:'MARA VELDT — OPEN GROUND',detail:'GALLERY I · UNTIL 27 SEPTEMBER'},
 {src:hero02,alt:'Two abstract paintings in the gallery enfilade',exhibition:'JONAS RHEE — AFTER WEATHER',detail:'ONLINE PREVIEW · AUTUMN 2026'},
 {src:hero03,alt:'A tall abstract painting in warm afternoon light',exhibition:'PRIVATE VIEWING ROOMS',detail:'BY APPOINTMENT · ANTWERP'},
];
function Hero(){const[active,setActive]=useState(0);useEffect(()=>{const timer=setInterval(()=>setActive(i=>(i+1)%heroSlides.length),6500);return()=>clearInterval(timer)},[]);const slide=heroSlides[active];return <section className="hero"><div className="heroMedia"><AnimatePresence initial={false}><motion.img key={slide.src} src={slide.src} alt={slide.alt} initial={{opacity:0,scale:1}} animate={{opacity:1,scale:1.025}} exit={{opacity:0}} transition={{opacity:{duration:1.15},scale:{duration:7,ease:'linear'}}}/></AnimatePresence></div><div className="shade"/><motion.div className="heroCopy" initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} transition={{duration:1,delay:.25}}><small>ANTWERP · EST. 2013</small><h1>Art that<br/><i>outlives</i> the room.</h1><p>Vant—Lore represents a focused roster of contemporary painters whose work rewards a longer look.</p><button onClick={()=>go('collection')}>Explore the collection <ArrowDownRight/></button></motion.div><AnimatePresence mode="wait"><motion.div key={active} className="heroSide" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}>{String(active+1).padStart(2,'0')} / {String(heroSlides.length).padStart(2,'0')}<br/><b>{slide.exhibition}</b><span>{slide.detail}</span></motion.div></AnimatePresence><div className="heroControls" aria-label="Hero slideshow">{heroSlides.map((s,i)=><button key={s.src} className={i===active?'active':''} onClick={()=>setActive(i)} aria-label={`Show slide ${i+1}`}><span/></button>)}</div><div className="scroll">SCROLL TO DISCOVER</div></section>}
function FeaturedWorks(){const rail=useRef(null);const move=direction=>rail.current?.scrollBy({left:direction*rail.current.clientWidth*.82,behavior:'smooth'});return <section className="featured"><div className="sectionHead"><small>SELECTED WORKS / 2024—26</small><h2>New to the collection</h2><p>Abstraction, figure, landscape and still life—held to one exacting standard.</p></div><div className="railWrap"><button className="railArrow railPrev" onClick={()=>move(-1)} aria-label="Previous artworks"><ArrowLeft size={18}/></button><div className="workRail" ref={rail}>{homepageWorks.map(w=><motion.article key={w.id} whileHover={{y:-10}} onClick={()=>go('collection')}><div className="num">{w.id} {w.genre&&<span>{w.genre}</span>}</div><Art tone={w.tone} image={w.image}/><div className="meta"><div><h3>{w.title}</h3><p>{w.artist}</p></div><span>{w.year}<br/>{w.medium}</span></div></motion.article>)}</div><button className="railArrow railNext" onClick={()=>move(1)} aria-label="Next artworks"><ArrowRight size={18}/></button></div></section>}
function Home(){return <>
 <Hero/>
 <section className="intro"><Reveal><small>THE GALLERY</small><h2>We believe a painting should change<br/>with the <i>life around it.</i></h2></Reveal><Reveal className="introText"><p>Since 2013, we have worked closely with emerging and established artists across Europe, placing significant works in considered private and institutional collections.</p><button onClick={()=>go('artists')}>Meet our artists <MoveRight/></button></Reveal></section>
 <FeaturedWorks/>
 <section className="exhibit"><Reveal className="exhibitArt"><Art tone="exhibit-silt"/></Reveal><Reveal className="exhibitCopy"><small>ON VIEW · GALLERY I</small><h2>Open Ground</h2><h3>Mara Veldt</h3><p>Veldt’s newest paintings hold geological time and human gesture in the same surface—scored, buried, and slowly revealed.</p><dl><dt>OPENING</dt><dd>14 June 2026</dd><dt>ON VIEW</dt><dd>Until 27 September</dd></dl><button onClick={()=>go('exhibitions')}>View exhibition <ArrowUpRight/></button></Reveal></section>
 <section className="quote"><Reveal><span>“</span><h2>We do not fill walls.<br/>We build <i>collections.</i></h2><p>— ELISE VAN LORE, FOUNDER</p></Reveal></section>
 <ViewingRoom/><JournalPreview/>
 </>}
function ViewingRoom(){return <section className="viewing"><Reveal className="viewingCopy"><small>ONLINE VIEWING ROOM · 04</small><h2>Surface / Memory</h2><p>A private digital presentation bringing together twelve works concerned with erasure, trace, and the physical intelligence of paint.</p><dl><dt>12 WORKS</dt><dd>4 ARTISTS</dd><dt>CURATED BY</dt><dd>ELISE VAN LORE</dd></dl><button onClick={()=>go('collection')}>Enter viewing room <ArrowUpRight/></button></Reveal><Reveal className="viewingVisual"><Art tone="view-grid"/><Art tone="view-mark"/></Reveal></section>}
function JournalPreview(){return <section className="journal"><div className="sectionHead"><small>NOTES & CONVERSATIONS</small><h2>From the journal</h2></div><div className="journalGrid">{[['IN THE STUDIO','The patience of pigment','A morning with Jonas Rhee in his Rotterdam studio.','journal-wash'],['ESSAY','Living with abstraction','On collecting slowly, and choosing with conviction.','journal-line'],['FIELD NOTE','Basel, after hours','Five works that stayed with us beyond the fair.','journal-night']].map((a,i)=><Reveal key={a[1]} delay={i*.08} className="story"><Art tone={a[3]}/><small>{a[0]} · 06.2026</small><h3>{a[1]}</h3><p>{a[2]}</p><button onClick={()=>go('journal')}>Read story <ArrowUpRight/></button></Reveal>)}</div></section>}
function SubPage({page}){const data={collection:['THE COLLECTION','Works for a longer conversation.','A living selection of paintings by the artists we represent. Availability and full dossiers are shared on request.'],artists:['REPRESENTED ARTISTS','Singular voices. Enduring practices.','Our programme brings together painters defined by material intelligence, rigor and a deeply personal visual language.'],exhibitions:['EXHIBITIONS','Ideas made physical.','Solo presentations and quiet dialogues shaped in close collaboration with our artists.'],journal:['JOURNAL','Looking, slowly.','Studio conversations, field notes and essays from the people who make, collect and live with art.'],visit:['ANTWERP · BELGIUM','Come and stay a while.','Our gallery is open Thursday through Saturday. Private viewings are available throughout the week.']}[page];return <><section className="subHero"><motion.small initial={{opacity:0}} animate={{opacity:1}}>{data[0]}</motion.small><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}}>{data[1]}</motion.h1><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.2}}>{data[2]}</motion.p></section>{page==='collection'&&<Collection/>}{page==='artists'&&<Artists/>}{page==='exhibitions'&&<Exhibitions/>}{page==='journal'&&<JournalPreview/>}{page==='visit'&&<Visit/>}</>}
function Collection(){const[filter,setFilter]=useState('All');const[selected,setSelected]=useState(null);const list=works.filter(w=>filter==='All'||w.status===filter);return <><div className="collectionTools"><div>{['All','Available','On hold'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><span>{list.length} works</span></div><section className="collectionGrid">{list.map((w,i)=><Reveal key={w.id} className={`collectionItem c${i}`}><button className="artButton" onClick={()=>setSelected(w)} aria-label={`View ${w.title} by ${w.artist}`}><Art tone={w.tone} image={w.image}/></button><small>{w.artist} · {w.year} <b>{w.status}</b></small><h3>{w.title}</h3><p>{w.medium}<br/>{w.size}</p><button onClick={()=>setSelected(w)}>View work <ArrowUpRight/></button></Reveal>)}</section><AnimatePresence>{selected&&<motion.div className="artModal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="dialog" aria-modal="true"><button className="modalClose" onClick={()=>setSelected(null)} aria-label="Close artwork details"><X/></button><div className="modalImage"><Art tone={selected.tone} image={selected.image}/></div><div className="modalInfo"><small>{selected.artist} · {selected.year}{selected.genre&&` · ${selected.genre}`}</small><h2>{selected.title}</h2><p>{selected.medium}<br/>{selected.size}</p><span>{selected.status}</span><p className="provenance">Signed and dated verso. Artist studio reference included. Worldwide delivery and installation coordinated by the gallery.</p><button onClick={()=>go('visit')}>Enquire about this work <ArrowUpRight/></button></div></motion.div>}</AnimatePresence></>}
function Artists(){return <section className="artistList">{['Mara Veldt','Jonas Rhee','Sofia Marin','Ivo Kers','Noor Abeni','Lucien Vale','Emilia Sanz','Ansel Devereux','Clara Mertens','Yuna Seo','Amina Kader','Elias Voss','Tess Nwosu'].map((n,i)=><motion.div key={n} whileHover={{paddingLeft:24}}><span>{String(i+1).padStart(2,'0')}</span><h2>{n}</h2><p>{['Belgium','South Korea / Netherlands','Spain','Belgium','France','United Kingdom','Spain','France','Belgium','South Korea','Morocco / France','Germany','United Kingdom / Nigeria'][i]}</p><ArrowUpRight/></motion.div>)}</section>}
function Exhibitions(){return <section className="exRows">{[['CURRENT','Open Ground','Mara Veldt','14.06—27.09.2026','ex-current'],['UPCOMING','Held Light','Sofia Marin','18.10—20.12.2026','ex-upcoming'],['ARCHIVE','The Weather Between','Jonas Rhee','08.02—19.04.2026','ex-archive']].map(e=><Reveal key={e[1]} className="exRow"><Art tone={e[4]}/><small>{e[0]}</small><div><h2>{e[1]}</h2><h3>{e[2]}</h3></div><p>{e[3]}</p><ArrowUpRight/></Reveal>)}</section>}
function Visit(){return <section className="visit"><div><Art tone="visit-map"/></div><div><small>VISITING HOURS</small><h2>Thursday—Saturday<br/>11:00—18:00</h2><p>Kattendijkdok 14<br/>2000 Antwerp<br/>Belgium</p><hr/><small>PRIVATE APPOINTMENTS</small><p>For collection consultations or a private viewing, write to studio@vantlore.gallery.</p><button>Plan your visit <ArrowUpRight/></button></div></section>}
function useElasticFooterCanvas(){useEffect(()=>{const root=document.documentElement;const update=()=>{const atEnd=window.scrollY+window.innerHeight>=root.scrollHeight-2;root.classList.toggle('at-page-end',atEnd)};update();addEventListener('scroll',update,{passive:true});addEventListener('resize',update);return()=>{removeEventListener('scroll',update);removeEventListener('resize',update);root.classList.remove('at-page-end')}},[])}
function App(){const get=()=>location.hash.replace('#','').replace('/','')||'home';const[page,setPage]=useState(get());useElasticFooterCanvas();useEffect(()=>{const h=()=>setPage(get());addEventListener('hashchange',h);return()=>removeEventListener('hashchange',h)},[]);return <div className="shell"><Nav page={page}/><AnimatePresence mode="wait"><motion.main id="content" key={page} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.35}}>{page==='home'?<Home/>:<SubPage page={page}/>}</motion.main></AnimatePresence><Footer/></div>}
createRoot(document.getElementById('root')).render(<App/>);
